---
title: "Escarificación"
author: "Grupo2"
format:
  html:
    toc: true
    toc-expand: true
    toc-depth: 4
    toc-location: left
    number-sections: true
    self-contained: true
    code-fold: true
    output-file: "ESM"
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  message: false
  echo: true
---

# Project Setup

```{r}
#| label:  setup

source('https://inkaverse.com/setup.r')
```

# Data import

```{r}
gs <- "https://docs.google.com/spreadsheets/d/1rnfI5GubetNELa6mLWgp4UGKzIpJlTmaXZTuS5ZE3CI/edit?pli=1&gid=112042476#gid=112042476" %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read(ss = .,sheet = "fb")
```

#Cálculo de índices de germinación
```{r}
# Install packages and dependencies

library(GerminaR)
library(factoextra)
library(dplyr)

# Prosopis data set

fb %>% 
   head(10) %>% 
   kable(caption = "fb_dataset")
```

```{r}

# germination analysis (ten variables)

gsm <- ger_summary(factors = c("escarificacion")
                   , SeedN = "seeds"
                   , evalName = "D"
                   , cumulative = FALSE
                   , data = fb
                   )

# Prosopis data set processed

gsm %>% 
  head(10) %>% 
  mutate(across(where(is.numeric), ~round(., 2))) %>% 
  kable(caption = "Function ger_summary performe ten germination indices")
```

# Anova
$$y = media + escarificación + error$$
##Porcentaje de germinación
```{r}
# analysis of variance

av_grp <- aov(grp ~ escarificacion, data = gsm)
Anova(av_grp)

# mean comparison test

mc_grp <- ger_testcomp(aov = av_grp
                       , comp = c("escarificacion")
                       , type = "tukey"
                       )

# data result

mc_grp$table %>% 
  mutate(
    across(where(is.numeric), ~ round(., 2))
  ) %>% 
  kable(
    caption = "Comparison of germination percentage among scarification treatments using Tukey test"
  )
```


```{r}
#Gráfico
grp <- mc_grp$table %>% 
   fplot(data = .
       , type = "bar"
       , x = "escarificacion"
       , y = "grp"
       , group = NULL
       , ylimits = c(0, 120, 20)
       , ylab = "Germinación ('%')"
       , xlab = "Tratamientos de escarificación"
       , legend = "top"
       , sigsize = 4
       , error = "ste"
       , sig = "sig"
       , color = T
       )

grp$layers[[1]]$aes_params$width <- 0.6

grp

 ggsave(plot =, "desing/grp.jpg")
```



##Velocidad de germinación
```{r}
# analysis of variance

avgsp <- aov(gsp ~ escarificacion, data = gsm)
Anova(avgsp)

# mean comparison test

mc_gsp <- ger_testcomp(aov = avgsp
                       , comp = c("escarificacion")
                       , type = "tukey"
                       )

# data result

mc_gsp$table %>% 
  mutate(
    across(where(is.numeric), ~ round(., 2))
  ) %>% 
  kable(
    caption = "Comparación de la velocidad de germinación mediante tratamientos de escarificación usando la prubea de Tukey"
  )
```


```{r}
#Gráfico
gsp <- mc_gsp$table %>% 
   fplot(data = .
       , type = "bar"
       , x = "escarificacion"
       , y = "gsp"
       , group = NULL
       , ylimits = c(0, 30, 10)
       , ylab = "Velocidad de germinación ('%')"
       , xlab = "Tratamientos de escarificación"
       , legend = "top"
       , sigsize = 4
       , error = "ste"
       , sig = "sig"
       , color = T
       )

gsp$layers[[1]]$aes_params$width <- 0.6

gsp

 ggsave(plot =, "desing/gsp.jpg")
```

##Tiempo medio de germinación
```{r}
## Mean Germination Time (MGT)

# analysis of variance

avmgt <- aov(mgt ~ escarificacion, data = gsm)
anova(avmgt)

# mean comparison test

mc_mgt <- ger_testcomp(aov = avmgt
                       , comp = c("escarificacion")
                       , type = "tukey")

# data result

mc_mgt$table %>% 
  mutate(
    across(where(is.numeric), ~ round(., 2))
  ) %>% 
  kable(
    caption = "Comparación del tiempo medio de germinación"
  )
```

```{r}
#Gráfico

# bar graphics for mean germination time

mgt <- mc_mgt$table %>% 
  fplot(data = .
       , type = "bar" 
       , x = "escarificacion"
       , y = "mgt"
       , group = NULL
       , ylimits = c(0,7, 1)
       , ylab = "Tiempo medio de germinación (días)"
       , xlab = "Tratamientos de escarificación"
       , sig = "sig"
       , error = "ste"
       , color = T
       )

mgt$layers[[1]]$aes_params$width <- 0.6

mgt

 ggsave(plot =, "desing/mgt.jpg")
```


##Sincronía de germinación
```{r}
# analysis of variance

avsyn <- aov(syn ~ escarificacion, data = gsm)
anova(avsyn)

# mean comparison test

mc_syn <- ger_testcomp(aov = avsyn
                       , comp = c("escarificacion")
                       , type = "tukey")

# data result

mc_syn$table %>% 
  mutate(
    across(where(is.numeric), ~ round(., 2))
  ) %>% 
  kable(
    caption = "Comparación de la sincronización"
  )


```

```{r}
#Gráfico

# bar graphics for mean germination time

syn <- mc_syn$table %>% 
   fplot(data = .
       , type = "bar" 
       , x = "escarificacion"
       , y = "syn"
       , group = NULL
       , ylimits = c(0,1.2, 0.2)
       , ylab = "Índice de sincronía de germinación"
       , xlab = "Tratamientos de escarificación"
       , sig = "sig"
       , error = "ste"
       , color = T
       )


syn$layers[[1]]$aes_params$width <- 0.6

syn

 ggsave(plot =, "desing/syn.jpg")
```

# PCA

```{r}
#| eval: false

dtx <- gsm

#extracción de factores y variables

names(dtx)

data_pca <- dtx[, c(4,10, 11, 12, 16)]

pca_datos <- data_pca %>%
  group_by(across(1)) %>% 
  summarise(across(1:4, mean, na.rm = TRUE))

#En caso haya unidades NA en la base de datos

pca_datos[is.na(pca_datos)] <- 0

```

  
```{r}
library(factoextra)
library(ggrepel)
library(cowplot)

mv <- PCA(
  X = pca_datos[, 2:5],
  scale.unit = TRUE,
  graph = FALSE
)

# Variables
var <- fviz_pca_var(
  mv,
  col.var = "cos2",
  gradient.cols = c("blue", "red", "darkgreen"),
  repel = TRUE
)

var

ind <- fviz_pca_ind(
  mv,
  habillage = pca_datos$escarificacion,
  palette = c("blue", "red", "darkgreen", "orange"),
  addEllipses = FALSE,
  repel = TRUE,
  label = "none", 
  legend.title = "Tratamientos"
)

ind

ind <- ind +
  geom_text_repel(
    aes(
      x = mv$ind$coord[, 1],
      y = mv$ind$coord[, 2],
      label = pca_datos$escarificacion
    ),
    size = 4,
    show.legend = FALSE
  )

# combinar
plot <- list(var, ind) %>% 
  plot_grid(plotlist = ., ncol = 2, labels = "auto")

ggsave(
  plot = plot,
  filename = "desing/PCA.jpg",
  units = "cm",
  width = 30,
  height = 15
)
```

